-- MySQL Script generated by MySQL Workbench
-- Wed Sep  5 15:43:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PDFsign
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PDFsign` ;

-- -----------------------------------------------------
-- Schema PDFsign
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PDFsign` DEFAULT CHARACTER SET utf8 ;
USE `PDFsign` ;

-- -----------------------------------------------------
-- Table `PDFsign`.`vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PDFsign`.`vendors` (
  `v_id` INT NOT NULL COMMENT 'id таблицы vendors',
  `v_site` VARCHAR(255) NULL DEFAULT NULL COMMENT 'хранятся адреса сайтов',
  PRIMARY KEY (`v_id`),
  UNIQUE INDEX `idtable1_UNIQUE` (`v_id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PDFsign`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PDFsign`.`customers` (
  `c_id` INT NOT NULL AUTO_INCREMENT COMMENT 'id таблицы customers',
  `customerN` VARCHAR(45) NULL DEFAULT NULL COMMENT 'номер или имя кастомера',
  `c_vendor_id` INT NOT NULL COMMENT 'связь с id таблицы vendors',
  PRIMARY KEY (`c_id`),
  UNIQUE INDEX `c_id_UNIQUE` (`c_id` ASC),
  INDEX `v_id_idx` (`c_vendor_id` ASC),
  CONSTRAINT `CustomersVendorsFK`
    FOREIGN KEY (`c_vendor_id`)
    REFERENCES `PDFsign`.`vendors` (`v_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `PDFsign`.`vendors`
-- -----------------------------------------------------
START TRANSACTION;
USE `PDFsign`;
INSERT INTO `PDFsign`.`vendors` (`v_id`, `v_site`) VALUES (1, 'https://www.amazon.com/s/ref=nb_sb_noss_2?url=search-alias%3Dinstant-video&field-keywords=');

COMMIT;


-- -----------------------------------------------------
-- Data for table `PDFsign`.`customers`
-- -----------------------------------------------------
START TRANSACTION;
USE `PDFsign`;
INSERT INTO `PDFsign`.`customers` (`c_id`, `customerN`, `c_vendor_id`) VALUES (1, 'Arnold', 1);

COMMIT;

